INSERT INTO Task(title, text, links, CategoryId) VALUES("Employer Competitive", "Review Employer Ready Vs. Employer Competitive Handout", '<a href="https://drive.google.com/file/d/0BwhzeIUMYf1nV2JQcGdkU3ktcnFBLUZ4X09VSXliTUtJZWsw/view" target="_blank">Employer Ready Vs. Employer Competitive</a>', 1);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Brand Yourself", "Develop a short brand statement for yourself. Use this guide as a resource", '<a href="https://docs.google.com/document/d/1YbihkYmOu3boCu1j-myd6bVWE4l8CA6C4ka3cJ5opfk/edit" target="_blank">Brand Statement</a>', 2);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Elevator Pitch", "Review the guide 'Elevator Pitch Overview & Tips", '<a href="https://docs.google.com/document/d/16XXEbvPRiYguEv8VFj1_Yb2yVHocw045KIfrrlg7Ejk/edit" target="_blank">Elevator Pitch</a>', 1);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Job List", "Review the possible web development jobs", '<a href="https://docs.google.com/document/d/1dRuhFFblO14kcYQZprOh7E6QRbInkGd2OjiJimr8JX4/edit" target="_blank">Developer Jobs</a>', 1);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Job Requirement", "Review the job requirements", '<a href="https://docs.google.com/document/d/1hGVbn-X1E8Q7ATrh12uoAu4UhBSKt2QRrv7QYoxHqQY/edit" target="_blank">Job Requirements</a>', 2);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Build Your Visibility", "Execute the action items on a weekly basis", '<a href="https://docs.google.com/document/d/1KezKeeXWHueyQH9PuHNsnTrM3khtvx43n_AGAu7hDhI/edit" target="_blank">Build Your Visibility</a>', 2);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Guide to Networking", "Read the guide and think about how to implement", '<a href="https://docs.google.com/document/d/1KezKeeXWHueyQH9PuHNsnTrM3khtvx43n_AGAu7hDhI/edit" target="_blank">Guide to Networking</a>', 4);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Email & LinkedIn Templates", "Review the following templates and use it for future communications", '<a href="https://docs.google.com/document/d/1byA9PCqxNAPsBCZ0CTiPQREaHyC0sRpZ16PwRzHZLCo/edit" target="_blank">Networking With Email & LinkedIn Templates</a>', 4);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Resume Criteria", "Read the following to understand what makes a great employer competitive resume", '<a href="https://docs.google.com/document/d/1WBvt7U0m6H8_SbqePkso6hobCwN596A4qwbEyJEGxVc/edit" target="_blank">Employer Competitive Resume</a>', 2);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Develop a New Resume", "Use the step by step guide to create a new resume", '<a href="https://docs.google.com/document/d/1fogLPXUEip5tLDcCxX72pMsTSPhsbBXsi7suxiWWkik/edit" target="_blank">Create a New Resume</a>', 2);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Resume Templates", "Whether you are new or a veteran, use these templates to optimize your exposure",'<a href="https://docs.google.com/document/d/1-9ZkBbeX9XIKTLpAnc8jktuFMYCX6YK8Zb-3lay_MyY/edit" target="_blank">Resume Templates</a>', 2);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Frequently Asked Questions", "Read the FAQ document for clarity on branding yourself",'<a href="https://docs.google.com/document/d/1uFp636S8CGqsFtsxPvHTSBDshPoK3NByQocG2JRAlng/edit" target="_blank">FAQ</a>', 1);
INSERT INTO Task(title, text, links, CategoryId) VALUES("Polish Your Portfolio", "Update your LinkedIn profile to meet the Employer Competitive standards. Use the following link to review how-to resources",'<a href="https://docs.google.com/document/d/1HqXPGpFijlO24HnS85L_08dcao6dE374B56MU471hVM/edit" target="_blank">FAQ</a>', 2);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("Review of Materials", "Ask a mentor or professional contact to review your Github, LinkedIn, and Portfolio. Use their feedback to revise materials. Check out the handout for suggestions.", '<a href="https://docs.google.com/document/d/17vxqkMVZ7oLfTBTIcRlitsY4ExNX43sbWxpam37meSA/edit" target="_blank">LinkedIn-For Web Developers</a>' '<a href="https://docs.google.com/document/d/1oViUbQx1gVVr18Oy8Y-BtOul8pcE7Qnq58zCG6CE5nQ/edit" target="_blank">GitHub-For Web Developers</a>' '<a href="https://docs.google.com/document/d/1PUluveAdLOh_LkQ1iPzF1xv6wkwEUV_QPEn3mLoCpDY/edit" target="_blank">Portfolio Tips</a>', 3); 

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("Interview Prep-Behavioral", "Use these videos on how to prepare for a behavioral interview.", '<a href="https://www.youtube.com/watch?v=mH3DaeJSwy4" target="_blank">Behavioral Interview Questions</a>','<a href="https://www.youtube.com/watch?v=qKBubKO-798" target="_blank">The Behavioral Interview</a>', 4); 

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("Interviews-What to Expect", "Read through these frequently asked questions about web dev interviews.", '<a href="https://docs.google.com/document/d/1oMXTR5RvfmM8CeUsUnmrT_QxPDDRG309Oe5sJU42Jnw/edit" target="_blank">Interview FAQ</a>', 3); 

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("Approaching the Interview", "This handout provides a step-by-step guide on how to ensure you are ready for interviews.", '<a href="https://docs.google.com/document/d/1XiEsYlEbiEJRdQINav3QaZ6DxlAIOKlC3LTkgcjDOug/edit" target="_blank">Preparing for the Interview</a>', 3);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("Attend a Mock Interview", "Sign up for and attend a mock interview in which you practice your interviewing skills and practice showcasing your skillset. See links below for some opportunities.", '<a href="https://careerservicesonlineevents.splashthat.com/" target="_blank">Mock Interview Events</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("Review Your Resume", "Use these resources to review your resume to be employer competitive.", '<a href="https://docs.google.com/document/d/1pyHgv7_7OfKODBLhLV_TQZDmjwTiWdfZi50xSyrajDc/edit" target="_blank">Mock Interview Events</a>' '<a href="https://docs.google.com/document/d/1wJ8_Min4A5ycjLzC2u1_T0m7qrnFwj7ybpnfuUUs5GE/edit" target="_blank">Mock Interview Events</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("Java Script Practice", "Complete Java Script exercises 1-4 at the link below.", '<a href="https://www.w3resource.com/javascript-exercises/" target="_blank">Java Script Exercises</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("Java Script Practice", "Complete Java Script exercises 5-8 at the link below.", '<a href="https://www.w3resource.com/javascript-exercises/" target="_blank">Java Script Exercises</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("Java Script Practice", "Complete Java Script exercises 9-12 at the link below.", '<a href="https://www.w3resource.com/javascript-exercises/" target="_blank">Java Script Exercises</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("Java Script Practice", "Complete Java Script exercises 13-16 at the link below.", '<a href="https://www.w3resource.com/javascript-exercises/" target="_blank">Java Script Exercises</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("React Practice", "Complete the React coding exercis at the link below. Don't look at the answer before you complete your solution!", '<a href="https://gist.github.com/gaearon/8fa9fdd2c4197ee0b52894877bf587a4" target="_blank">React Interview Practice</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("React Learning", "Review your knowledge of React by completing Chapters 1-2 on React's website. Read through each chapter and work out the examples on your local IDE. Keep notes of your thinking, mistakes, and insights.", '<a href="https://reactjs.org/docs/hello-world.html" target="_blank">React Learning Page</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("React Learning", "Review your knowledge of React by completing Chapters 3-4 on React's website. Read through each chapter and work out the examples on your local IDE. Keep notes of your thinking, mistakes, and insights.", '<a href="https://reactjs.org/docs/hello-world.html" target="_blank">React Learning Page</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("React Learning", "Review your knowledge of React by completing Chapters 5-6 on React's website. Read through each chapter and work out the examples on your local IDE. Keep notes of your thinking, mistakes, and insights.", '<a href="https://reactjs.org/docs/hello-world.html" target="_blank">React Learning Page</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("React Learning", "Review your knowledge of React by completing Chapters 7-8 on React's website. Read through each chapter and work out the examples on your local IDE. Keep notes of your thinking, mistakes, and insights.", '<a href="https://reactjs.org/docs/hello-world.html" target="_blank">React Learning Page</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("React Learning", "Review your knowledge of React by completing Chapters 9-10 on React's website. Read through each chapter and work out the examples on your local IDE. Keep notes of your thinking, mistakes, and insights.", '<a href="https://reactjs.org/docs/hello-world.html" target="_blank">React Learning Page</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("React Learning", "Review your knowledge of React by completing Chapters 11-12 on React's website. Read through each chapter and work out the examples on your local IDE. Keep notes of your thinking, mistakes, and insights.", '<a href="https://reactjs.org/docs/hello-world.html" target="_blank">React Learning Page</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("React Today", "Read this post on React and bookmark any links you may find interesting.", '<a href="https://tylermcginnis.com/react-interview-questions/" target="_blank">React</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("React Mini App", "Complete this mini web page in react following the instructions. You will check you answers with the answer key provided at the bottom of the page. Remember to take breaks in between!", '<a href="https://github.com/tylermcginnis/react-fundamentals-curriculum" target="_blank">Basic React Web Page </a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("React DIY", "Complete one project of your choice from the following page. Note that projects are listed in order of ascending complexity.", '<a href="https://daveceddia.com/react-practice-projects/" target="_blank">React Projects</a>', 4);

INSERT INTO Tasks (title, text, links, categoryId) VALUES ("React DIY", "Complete one other project of your choice from the following page. Note that projects are listed in order of ascending complexity. Come back to this on your own time if you are interested!", '<a href="https://daveceddia.com/react-practice-projects/" target="_blank">React Projects</a>', 4);
